CREATE TABLE `ex9-1`(
`item_id` INT,
`category` INT,
`item_name` VARCHAR(50),
`price` INT
);

INSERT INTO `ex9-1` (`item_id`, `category`, `item_name`, `price`)
VALUES
 (1003, 1, 'Mango', 10000),
 (1000, 1, 'Apple', 8000),
 (1002, 1, 'Orange', 4000),
 (1004, 1, 'Tomato', 1500),
 (1005, 2, 'Kiwi', 6000),
 (1001, 2, 'Banana', 6000);

-- 순위 함수 연습
SELECT *
 , RANK() OVER (PARTITION BY item_id ORDER BY price DESC) AS RANK_COL
 , DENSE_RANK() OVER (PARTITION BY item_id ORDER BY price DESC) AS DENSE_RANK_COL
 , ROW_NUMBER() OVER (PARTITION BY item_id ORDER BY price DESC) AS ROW_NUMBER_COL
FROM `ex9-1`
ORDER BY category ASC, price DESC;

-- 집계 함수 연습
SELECT *, 
SUM(price) OVER (PARTITION BY category) AS SUM_COL,
AVG(price) OVER (PARTITION BY category) AS AVG_COL,
MAX(price) OVER (PARTITION BY category) AS MAX_COL,
min(price) OVER (PARTITION BY category) AS MIN_COL
FROM `ex9-1`;

SELECT *,
FIRST_VALUE(price) OVER (PARTITION BY category ORDER BY item_name DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS FIRST_VALUE_COL,
LAST_VALUE(price) OVER (PARTITION BY category ORDER BY item_name DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_VALUE_COL
FROM `ex9-1`;

SELECT *,
FIRST_VALUE(price) OVER (PARTITION BY category ORDER BY item_name DESC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS FIRST_VALUE_COL,
LAST_VALUE(price) OVER (PARTITION BY category ORDER BY item_name DESC ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS LAST_VALUE_COL
FROM `ex9-1`;

SELECT *,
 LAG(price, 2) OVER (ORDER BY price DESC) AS LAG_COL,
 LEAD(price, 2) OVER (ORDER BY price DESC) AS LEAD_COL
FROM `ex9-1`
ORDER BY price DESC;
